name: demoProject
description: ''
version: 0.0.1
author: vickyviji3546@gmail.com
language: python
buildSystem: wheel
pipelines:
  pipelines/pipelineDemo:
    name: pipelineDemo
    description: ''
    author: vickyviji3546@gmail.com
    mode: batch
    language: python
    createdAt: '2022-10-10 11:08:12'
    datasets:
      inputs:
      - 3574/datasets/OrdersDataset
      outputs: []
    dependencies: {}
datasets:
  datasets/OrdersDataset:
    name: OrdersDataset
    description: ''
    author: vickyviji3546@gmail.com
    createdAt: '2022-10-11 06:46:08'
    physicalDatasets:
      dev:
        fabricId: 1070
        datasetType: File
        description: ''
        author: vickyviji3546@gmail.com
        createdAt: '2022-10-11 06:46:08'
templates: {}
jobs: {}
libraries: []
subgraphs: {}
dependencies: '[]'
